export const navLinks = [
    {
        Icon:"",
        href:"/",
        text:"Home",
        description:""
    },
    {
        Icon:"",
        href:"/about",
        text:"About",
        description:""
    },
    {
        Icon:"",
        href:"/projects",
        text:"Projects",
        description:""
    },
    {
        Icon:"",
        href:"/blog",
        text:"Blog",
        description:""
    },
    {
        Icon:"",
        href:"/contact",
        text:"Contact",
        description:""
    },
];